### ISSUE TITLE
isocodes.languages.get(name="Spanish") is {}

### ISSUE THREAD

**Issue by ekalosak** [Atem18/isocodes#194]
Thank you for pushing `pycountry` into the future!! I have a bug to report.

Using latest `isocodes`, Python 3.11.4
```
import isocodes
assert isocodes.languages.get(name="Spanish")
```
^ the assert fails.

Direct string matches are a pain 😅
[Here's the line](https://github.com/Atem18/isocodes/blob/main/isocodes/share/iso-codes/json/iso_639-2.json#L1776) that shows the data has "Spanish; ..." rather than "Spanish" alone. Something like iso639's `match` functionality would supercharge this library.

**Comment by Atem18** [comment]
@ekalosak Thanks a lot for the bug report, I will have a look.

**Comment by Atem18** [comment]
@ekalosak This should be fixed in the version 2023.08.29.

**Comment by ekalosak** [comment]
See PR comment; tl;dr that PR fixes the issue but is still brittle. Thank you!!!!

**Comment by Atem18** [comment]
> See PR comment; tl;dr that PR fixes the issue but is still brittle. Thank you!!!!

No problem, thanks for using this library ! :)
